name: Build

permissions: {}

on:
  schedule:
    - cron: 0 18 * * * # 2:00 UTC+8 everyday
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write # required to push
    runs-on: ubuntu-26.04
    timeout-minutes: 10
    env:
      filename: bubble.svg
    steps:
      - uses: actions/checkout@v7
        with:
          ref: output
          persist-credentials: true
          fetch-depth: 2

      - name: setup
        id: setup-mise
        uses: jdx/mise-action@v4
        with:
          install: true
          cache: true
          cache_key_prefix: "nightly"
          mise_toml: |
            [settings.npm]
            package_manager = "pnpm"
            shell_out = true
            [tools]
            node = "lts"
            pnpm = "latest"
            "npm:pacman-contribution-graph" = "latest"

      - name: generate
        run: pacman-contribution-graph --game puzzle-bobble --username ${{ github.repository_owner }} --platform github --gameTheme github-dark --output "${filename}"

      - name: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit --amend --no-edit
          git push origin output --force
