name: Build

permissions: {}

on:
  schedule:
    - cron: 0 18 * * * # 2:00 UTC+8 everyday
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write # required to push
    runs-on: ubuntu-26.04
    strategy:
      matrix:
        python-version: ["3.14"]
    timeout-minutes: 10
    env:
      filename: invader.webp
    steps:
      - uses: actions/checkout@v7
        with:
          ref: output
          persist-credentials: true
          fetch-depth: 2

      - name: setup
        id: setup-mise
        uses: jdx/mise-action@v4
        with:
          install: true
          cache: true
          cache_key_prefix: "nightly"
          tool_versions: |
            python ${{ matrix.python-version }}
            uv latest
            pipx:gh-space-shooter latest

      - name: generate
        run: gh-space-shooter ${{ github.repository_owner }} --strategy random --output "${filename}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit --amend --no-edit
          git push origin output --force
